title: Goal Kit Documentation
description: Documentation for Goal Kit - Goal-Driven Development Toolkit
theme: jekyll-theme-primer

markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"