site_name: Goal Kit Documentation
site_description: Goal-Driven Development Toolkit
site_author: Nom-nom-hub
repo_url: https://github.com/Nom-nom-hub/goal-kit
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: green
    accent: green

nav:
  - Home: index.md
  - Goal-Driven Development: goal-driven.md
  - Comparison: comparison.md
  - Examples: examples.md
  - Table of Contents: toc.md
  - README: README.md
  - Commands:
    - Adapt Command: adapt-command.md
    - Agent Profile Command: agent-profile-command.md
    - Analytics Command: analytics-command.md
    - Analyze Command: analyze-command.md
    - Benchmark Command: benchmark-command.md
    - Collaborate Command: collaborate-command.md
    - Config Command: config-command.md
    - Dependencies Command: dependencies-command.md
    - Execute Command: execute-command.md
    - Explore Command: explore-command.md
    - Goal Command: goal-command.md
    - Help Command: help-command.md
    - Insights Command: insights-command.md
    - Learn Command: learn-command.md
    - Measure Command: measure-command.md
    - Methodology Command: methodology-command.md
    - Milestones Command: milestones-command.md
    - Onboard Command: onboard-command.md
    - Plan Command: plan-command.md
    - Prioritize Command: prioritize-command.md
    - Reflect Command: reflect-command.md
    - Report Command: report-command.md
    - Research Command: research-command.md
    - Risk Command: risk-command.md
    - Schedule Command: schedule-command.md
    - Security Command: security-command.md
    - Strategies Command: strategies-command.md
    - Tasks Command: tasks-command.md
    - Test Command: test-command.md
    - Track Command: track-command.md
    - Validate Command: validate-command.md
    - Vision Command: vision-command.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight