site_name: Goal Kit Documentation
site_description: Goal-Driven Development Toolkit
site_author: Nom-nom-hub
repo_url: https://github.com/Nom-nom-hub/goal-kit
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: green
    accent: green

nav:
  - Home: index.md
  - Goal-Driven Development: goal-driven.md
  - Comparison: comparison.md
  - Examples: examples.md
  - Table of Contents: toc.md
  - README: README.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight